version: '3'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - ./db:/var/lib/mysql
    wordpress:
        image: wordpress
        restart: always
        depends_on:
            - db
        environment:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_USER: exampleuser
          WORDPRESS_DB_PASSWORD: examplepass
          WORDPRESS_DB_NAME: exampledb
        volumes:
            - ./wordpress:/var/www/html

    rproxy:
        image: nginx
        restart: always
        depends_on:
            - wordpress
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/ssl/nginx-selfsigned.crt:/etc/nginx/cert.crt
            - ./nginx/ssl/nginx-selfsigned.key:/etc/nginx/cert.key